from pptx.util import Cm

# Size definitions
SLIDE_WIDTH = Cm(21)
SLIDE_HEIGHT = Cm(29.7)

HEADER_FONT = Cm(0.5)
CHART_TITLE_FONT = Cm(0.4)
CHART_AXIS_FONT = Cm(0.3)
CHART_LABEL_FONT = Cm(0.3)
TABLE_HEADER_FONT = Cm(0.35)
TABLE_BODY_FONT = Cm(0.3)
BULLET_FONT = Cm(0.36)
DISCLAIMER_FONT = Cm(0.28)
TAGLINE_FONT = Cm(0.35)

# Margins and positions
HEADER_LEFT = Cm(1)
HEADER_TOP = Cm(1)
HEADER_WIDTH = Cm(6)
HEADER_HEIGHT = Cm(1)

CHART_LEFT = Cm(1)
CHART_TOP = Cm(2.5)
CHART_WIDTH = Cm(9)
CHART_HEIGHT = Cm(8)

TABLE_LEFT = Cm(11.5)
TABLE_TOP = Cm(2.5)
TABLE_WIDTH = Cm(8.5)
TABLE_HEIGHT = Cm(8)
TABLE_COL_WIDTHS = [Cm(6), Cm(2.5)]

SECOND_TABLE_LEFT = Cm(1)
SECOND_TABLE_TOP = Cm(11)
SECOND_TABLE_WIDTH = Cm(19)
SECOND_TABLE_HEIGHT = Cm(4.5)
SECOND_TABLE_COL_WIDTHS = [Cm(4), Cm(15)]

WHAT_IN_IT_LEFT = Cm(1)
WHAT_IN_IT_TOP = Cm(17)
WHAT_IN_IT_WIDTH = Cm(11.5)
WHAT_IN_IT_HEIGHT = Cm(10)

FOOTER_FULL_LEFT = Cm(0)
FOOTER_FULL_TOP = Cm(27.7)
FOOTER_FULL_WIDTH = Cm(21)
FOOTER_FULL_HEIGHT = Cm(2)

DISCLAIMER_LEFT = Cm(0.5)
DISCLAIMER_TOP = Cm(27.9)
DISCLAIMER_WIDTH = Cm(10.5)
DISCLAIMER_HEIGHT = Cm(1.6)

TAGLINE_LEFT = Cm(11)
TAGLINE_TOP = Cm(27.9)
TAGLINE_WIDTH = Cm(10)
TAGLINE_HEIGHT = Cm(1.6)