importantColumns = [
    # Usernames
    "USERNAME",
    "HUMAN_NAME",
    # Subdomains & Domains
    "DOMAIN_NAME",
    "DOMAIN_NAME_PARENT",
    "SIMILARDOMAIN",
    "AFFILIATE_DOMAIN_NAME",
    "CO_HOSTED_SITE_DOMAIN",
    "INTERNET_NAME",
    "AFFILIATE_INTERNET_NAME",
    # Open Ports
    "TCP_PORT_OPEN",
    "TCP_PORT_OPEN_BANNER",
    # Directories/URLs
    "LINKED_URL_INTERNAL",
    "LINKED_URL_EXTERNAL",
    "URL_JAVASCRIPT",
    "URL_FORM",
    "URL_STATIC",
    "URL_UPLOAD",
    # Hashing/Security
    "HASH",
    "SSL_CERTIFICATE_RAW",
    # Additional Critical Security Fields
    "BLACKLISTED_IPADDR",
    "MALICIOUS_IPADDR",
    "BLACKLISTED_INTERNET_NAME",
    "MALICIOUS_INTERNET_NAME",
    "BLACKLISTED_AFFILIATE_IPADDR",
    "MALICIOUS_AFFILIATE_IPADDR",
    # Network Infrastructure
    "IP_ADDRESS",
    "AFFILIATE_IPADDR",
    "NETBLOCK_MEMBER",
    "BGP_AS_MEMBER",
    # Web Technology Stack
    "WEBSERVER_TECHNOLOGY",
    "WEBSERVER_BANNER",
    "URL_WEB_FRAMEWORK",
    "WEB_ANALYTICS_ID",
    # Contact Information
    "EMAILADDR",
    "AFFILIATE_EMAILADDR",
    "PHONE_NUMBER",
    "PHYSICAL_ADDRESS",
]

# importantColumns = [
#     "SIMILARDOMAIN_WHOIS", "AFFILIATE_DOMAIN_WHOIS", "CO_HOSTED_SITE_DOMAIN_WHOIS", "DOMAIN_WHOIS", 
#     "TARGET_WEB_CONTENT", "PHONE_NUMBER", "RAW_FILE_META_DATA", "AFFILIATE_INTERNET_NAME", 
#     "CO_HOSTED_SITE", "INTERNET_NAME", "AFFILIATE_IPADDR", "PHYSICAL_ADDRESS", "AFFILIATE_DOMAIN_NAME", 
#     "HTTP_CODE", "AFFILIATE_IPV6_ADDRESS", "NETBLOCK_MEMBER", "IP_ADDRESS", "TCP_PORT_OPEN", 
#     "PROXY_HOST", "PHYSICAL_COORDINATES", "BGP_AS_MEMBER", "ACCOUNT_EXTERNAL_OWNED", 
#     "AFFILIATE_WEB_CONTENT", "AFFILIATE_DESCRIPTION_CATEGORY", "WEBSERVER_BANNER", 
#     "URL_WEB_FRAMEWORK", "HUMAN_NAME", "SSL_CERTIFICATE_RAW", "AFFILIATE_COMPANY_NAME", 
#     "BLACKLISTED_AFFILIATE_INTERNET_NAME", "MALICIOUS_AFFILIATE_INTERNET_NAME", 
#     "BLACKLISTED_SUBNET", "MALICIOUS_SUBNET", "WEB_ANALYTICS_ID", "COMPANY_NAME", 
#     "AFFILIATE_DESCRIPTION_ABSTRACT", "SOCIAL_MEDIA", "GEOINFO", "MALICIOUS_AFFILIATE_IPADDR", 
#     "DOMAIN_REGISTRAR", "PUBLIC_CODE_REPO", "WEBSERVER_TECHNOLOGY", "BLACKLISTED_INTERNET_NAME", 
#     "MALICIOUS_INTERNET_NAME", "TCP_PORT_OPEN_BANNER", "BLACKLISTED_AFFILIATE_IPADDR", 
#     "BLACKLISTED_IPADDR", "MALICIOUS_IPADDR", "COUNTRY_NAME", "HASH", "RAW_RIR_DATA", 
#     "AFFILIATE_EMAILADDR", "PROVIDER_MAIL", "TARGET_WEB_CONTENT_TYPE", "USERNAME", 
#     "CO_HOSTED_SITE_DOMAIN", "INTERNET_NAME_UNRESOLVED", "SIMILARDOMAIN", "DOMAIN_NAME_PARENT", 
#     "RAW_DNS_RECORDS", "DOMAIN_NAME", "LINKED_URL_INTERNAL", "LINKED_URL_EXTERNAL", 
#     "URL_JAVASCRIPT", "URL_FORM", "PROVIDER_JAVASCRIPT", "URL_STATIC", "URL_UPLOAD", 
#     "EMAILADDR", "WEBSERVER_STRANGEHEADER", "PROVIDER_DNS", "DNS_TEXT", "DNS_SPF", 
#     "WEBSERVER_HTTPHEADERS"
# ]
    
# importantColumns = [
#     "USERNAME","HASH","PHONE_NUMBER"
# ]